project:
  type: book

book:
  title: "Probability and Statistics"
  author: "Swapnaneel Patra"
  date: "11/15/2025"
  chapters:
    - index.qmd
    - probability.qmd
    - references.qmd
        

bibliography: references.bib
csl: styles/ieee.csl
number-depth: 0

format:
  html:
    theme: darkly
    css: styles/custom.css
    number-sections: true
    # smooth-scroll: true
    # toc: true
    # toc-depth: 2
    # toc-expand: true

  pdf:
    documentclass: scrreprt
